services:
  - type: web
    name: medicare-platform
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: medicare.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: POSTGRES_DB
        fromDatabase:
          name: medicare-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: medicare-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: medicare-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: medicare-db
          property: host
      - key: REDIS_URL
        value: redis://red-fake:6379

databases:
  - name: medicare-db
    databaseName: medicare
    user: medicare_user
    plan: free
